// This file is autogenerated by VESC Tool

#ifndef CONFXML_H_
#define CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_MC_CONFIGURATION__SIZE		31620

// Variables
extern uint8_t data_mc_configuration_[];

// CONFXML_H_
#endif
