// This file is autogenerated by VESC Tool

#ifndef CONFPARSER_H_
#define CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define MC_CONFIGURATION_SIGNATURE		1250443276
#define SERIALIZED_CONFIG_LENGTH	488

// Functions
int32_t confparser_serialize_mc_configuration(uint8_t *buffer, const mc_configuration *conf);
bool confparser_deserialize_mc_configuration(const uint8_t *buffer, mc_configuration *conf);
void confparser_set_defaults_mc_configuration(mc_configuration *conf);

// CONFPARSER_H_
#endif
