// This file is autogenerated by VESC Tool

#ifndef CONFXML_H_
#define CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_CONFGENERATOR__SIZE		31885

// Variables
extern uint8_t data_confgenerator_[];

// CONFXML_H_
#endif
