// This file is autogenerated by VESC Tool

#ifndef CONFPARSER_H_
#define CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define CONFGENERATOR_SIGNATURE		1267460557
#define SERIALIZED_CONFIG_LENGTH	494

// Functions
int32_t confparser_serialize_confgenerator(uint8_t *buffer, const confgenerator *conf);
bool confparser_deserialize_confgenerator(const uint8_t *buffer, confgenerator *conf);
void confparser_set_defaults_confgenerator(confgenerator *conf);

// CONFPARSER_H_
#endif
