// This file is autogenerated by VESC Tool

#ifndef CONFGENERATOR_H_
#define CONFGENERATOR_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define CONFGENERATOR_SIGNATURE		1250443276
#define SERIALIZED_CONFIG_LENGTH	488

// Functions
int32_t confgenerator_serialize_confgenerator(uint8_t *buffer, const confgenerator *conf);
bool confgenerator_deserialize_confgenerator(const uint8_t *buffer, confgenerator *conf);
void confgenerator_set_defaults_confgenerator(confgenerator *conf);

// CONFGENERATOR_H_
#endif
